spring:
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${URL:jdbc:mariadb://localhost/resume_dev?useSSL=false&characterEncoding=utf8}
    username: ${USERNAME:user}
    password: ${PASSWORD:password}
config:
  app-id: ${APPID:cli_a384ab309178d00c}
  app-secret: ${APPSECRET:wiZiveYzG1acpHXkzYwZWdvBumqmk3EL}
  algo-secret: ${ALGOSECRET:b5dc3419aed1ad2d6dffd8c53ea19e1f42fc07e9e8b5b221a34e552cdf13f173}
